export const locale = {
    lang: 'fa',
    data: {
        'Form': {
            'FORMS': {
                'TITLE': 'فرم ها',
                'SEARCH': "جستجو",
            },
            'UNPROCESSED_FORMS': {
                'TITLE': 'فرم پردازش نشده',
                'ID': 'شناسه',
                'SUBMISSION_DATE': 'تاریخ ارسال',
                'CLIENT_NAME': 'نام مشتری',
                'CLIENT_NUMBER': 'شماره مشتری',
                'PHONE_NUMBER':'شماره تلفن',
                'STATUS': 'وضعیت',
                'SHOW_FORM': 'نمایش فرم',
                'PROCESS': 'فرم فرآیند',
                'NOTELIGIBLE': 'فاقد شرایط',
                'EDIT': 'ویرایش',
                'EMAIL': 'ایمیل',
                'DELETE': 'حذف',
                'MORE_INFO': 'اطلاعات بیشتر',
                'REJECT': 'مردود',
                'CONSULTATION': 'مشاوره',
                'CONTRACT': 'قرارداد',
                'LOSTLEAD':'سرب گم شده',
                'FOLLOWUP':'پیگیری'
            },
            'PROCESSED_FORMS': {
                'TITLE': 'فرم های پردازش شده',
                'ID': 'شناسه',
                'SUBMISSION_DATE': 'تاریخ ارسال',
                'ARRIVAL_DATE': 'تاریخ ورود',
                'PROCESS_DATE': 'تاریخ پردازش',
                'CLIENT_NAME': 'نام مشتری',
                'CLIENT_NUMBER': 'شماره مشتری',
                'PHONE_NUMBER':'شماره تلفن',
                'STATUS': 'وضعیت',
                'EMAIL': 'ایمیل',
                'UNPROCESSED': 'پردازش نشده',
                'SHOW_FORM': 'نمایش فرم',
                'PROCESS': 'فرم فرآیند',
                'EDIT': 'ویرایش',
                'DELETE': 'حذف',
                'MORE_INFO': 'اطلاعات بیشتر',
                'NOTELIGIBLE': 'فاقد شرایط',
                'REJECT': 'مردود',
                'CONSULTANT': 'مشاور',
                'CONSULTATION': 'مشاوره',
                'CONTRACT': 'قرارداد',
                'LOSTLEAD':'سرب گم شده',
                'FOLLOWUP':'پیگیری'
            },
            'CONTRACTED_FORMS': {
                'SUBMISSION_DATE': 'تاریخ ارسال',
                'CLIENT_NAME': 'نام مشتری',
                'CLIENT_NUMBER': 'شماره مشتری',
                'PHONE_NUMBER':'شماره تلفن',
                'STATUS': 'وضعیت',
                'TITLE': 'قراردادها',
                'SHOW_FORM': 'نمایش فرم',
                'PROCESS': 'بررسی',
                'EMAIL': 'ایمیل',
                'NOTELIGIBLE': 'فاقد شرایط',
                'EDIT': 'ویرایش',
                'DELETE': 'حذف',
                'MORE_INFO': 'اطلاعات بیشتر',
                'REJECT': 'مردود',
                'CONTRACT': 'قرارداد',
                'CONSULTATION': 'مشاوره',
                'UNPROCESSED': 'بررسی نشده',
                'LOSTLEAD':'سرب گم شده',
                'FOLLOWUP':'پیگیری'
            }
        },
        'Add_Edit_Form': {
            'TITLE': 'فرم درخواست مشاوره',
            'APPLICANT': 'متقاضی مهاجرت به کشور استرالیا',
            'SPOUSE': 'همسر',
            'BACK': 'صفحه قبل',
            'FORM': 'فرم',
            "PAYMENTSTITLE": "شرایط پرداخت",
            "PAYMENTS": {
                "INSTALLMENTSLABEL": "شرایط پرداخت قید شده در قرارداد",
                "SAVETEMPLATE": "حفظ متن",
                "ADDPAID": "افزایش مبلغ",
                "DELETEPAID": "حذف مبلغ",
                "NOTE": 'توضیحات',
                "VALUE": 'مبلغ',
            },
            'STEP_0': {
                'LABEL': 'مشخصات',
                'FNAME': 'نام',
                'LNAME': 'نام خانوادگی',
                'EMAIL': 'ایمیل',
                'MOBILE': 'موبایل',
                'MARITAL_STATUS': 'وضعیت تاهل',
                'CHILDREN_NUM': 'تعداد فرزندان',
                'BIRTH_DATE': 'تاریخ تولد',
                'SKYPE_ID': 'نام کاربری اسکایپ',
                "WITHPARTNER": "با همسر",
                "WITHOUTPARTNER": "بدون همسر",
                'MARRIED': 'متاهل',
                'SEPARETED': ' متارکه کرده',
                'DEVORCED': 'طلاق گرفته',
                'WIDOWED': 'بیوه',
                'NEVER_MARRIED': 'هرگز ازدواج نکرده',
                'SUBLABEL': 'اطلاعات فردی متقاضی و همسر',
                'ENAME': 'نام با حروف انگلیسی',
                'ESNAME': 'نام خانوادگی با حروف انگلیسی',
                'FSNAME': 'نام خانوادگی',
                'PHONE': 'تلفن ثابت',
                'FADDRESS': 'نشانی منزل',
                'EADDRESS': 'نشانی منزل با حروف انگلیسی',
            },
            'STEP_1': {
                "Writing": "نوشتن",
                "Listening": "گوش دادن",
                "Reading": "خواندن",
                "Speaking": "صحبت کردن",
                "Overall": "به طور کلی",
                'LABEL': 'سطح زبان انگلیسی',
                'ENGLISH_LEVEL': 'با زبان انگلیسی چقدر آشنایی دارید؟',
                'EXCELLENT': 'عالی',
                'GOOD': 'خوب',
                'MEDIUM': 'متوسط',
                'EN_SCORE': 'نمره آیلتس/تافل/پی تی ای خود را وارد کنید',
                'SUBLABEL': 'لطفا سطح زبان انگلیسی خود را مشخص نمایید',
                'WEAK': 'ضعیف',
            },
            'STEP_2': {
                "AssociateDegree": "کاردانی",
                "BachelorDegree": "کارشناسی",
                "MasterDegree": "کارشناسی ارشد",
                "PHDDegree": "دکترا",
                'LABEL': 'سطح تحصیلات',
                'DEGREE': 'مدرک تحصیلی',
                'ASSISTANT': 'کاردانی',
                'UNDER_GRAD': 'کارشناسی',
                'MASTER': 'کارشناسی ارشد',
                'DOC': 'دکترا',
                'FIELD': 'رشته',
                'UNIVERSITY': 'نام دانشگاه',
                'EDU_PLACE': 'واحد دانشگاهی',
                'YEAR_GRAD': 'سال فارغ التحصیلی',
                'SUBLABEL': 'لطفا سوابق تحصیلات عالی خود را مشخص نمایید',
            },
            'STEP_3': {
                'LABEL': 'میزان سابقه کاری',
                'RELATED_STUDY': 'مرتبط با رشته تحصیلی',
                'UNRELATED_STUDY': 'غیر مرتبط با رشته تحصیلی',
                'INSURANCE': 'با بیمه',
                'NOINSURANCE': 'بدون بیمه',
                'FIELD_ACTIVITY': 'زمینه فعالیت',
                'YEAR': 'سال',
                'SUBLABEL': 'لطفا سوابق کاری خود را مشخص نمایید',
                'FIELDOfWork': 'زمینه کاری',

                "REDYPAID": "سالهای مرتبط با رشته تحصیلی و با دریافت دستمزد ",
                "REDYNPAID": "سالهای مرتبط با رشته تحصیلی و بدون دریافت دستمزد",
                "NREDYPAID": "سالهای غیر مرتبط با رشته تحصیلی و با دریافت دستمزد",
                "NREDYNPAID": "سالهای غیر مرتبط با رشته تحصیلی و بدون دریافت دستمزد"
            },
            'STEP_4': {
                'LABEL': 'خدمت نظام وظیفه',
                'SUBLABEL': 'در صورت مشمول بودن، وضعیت خدمت نظام وظیفه خود را مشخص نمایید',
                'STATUS': 'وضعیت',
                'FINISHED': 'دارای پایان خدمت',
                'EXEMPTION': 'معافیت',
                'PLACE': 'محل خدمت',
                'FROM': 'از تاریخ',
                'TO': 'تا تاریخ',
                'EXEMPTIONREASON': 'در صورت معافیت دلیل آن را بفرمایید'
            },
            'STEP_5': {
                'LABEL': 'وضعیت سلامت',
                'SUBLABEL': 'لطفا وضعیت سلامتی و پزشکی خود را مشخص نمایید',
                'SIGNIFICANT': 'بیماری های مهم فعلی',
                'SURGERY': 'عمل جراحی در گذشته یا آینده',
            },
            'STEP_6': {
                'LABEL': 'فامیل در استرالیا',
                'SUBLABEL': 'آیا از اقوام شما یا همسرتان کسی در استرالیا زندگی میکند؟',
                'CITIZEN': 'تبعه استرالیا',
                'PERMANENTRES': 'دارای اقامت دائم',
                'TEMPORARYRES': 'دارای اقامت موقت',
                'STUDENTASSYLUM': ' دانشجو یا پناهنده',

                'RELATION': 'نسبت ایشان با شما',
                'LIVINGSTATE': 'ایالت محل زندگی ایشان در استرالیا',
                'LIVINGCITY': 'شهر محل زندگی ایشان در استرالیا',
                'VISATYPE': 'نوع ویزای ایشان'
            },
            'STEP_7': {
                'LABEL': 'کاربر',
                'TBADMIN': 'مطلب ارسالی از کاربر برای متقاضی در متن ایمیل',
                'TBNOTES': 'توضیحات داخلی در مورد متقاضی',
                'MAINAPPLICATION': 'متقاضی اصلی پرونده',
                'APPLICANT': 'متقاضی',
                "CURRENCY": "واحد پول",
                'SPOUSE': 'همسر',
                'TOTALPOINTS': 'جمع امتیازات',
                'DEPENDANT': 'متقاضی همراه',
                'OCCUPATIONTOBEASSESSED': 'شغل مورد ارزیابی',
                'YEAROFWORKEXPERIENCE': 'سالهای قابل ارائه برای سابقه کار',
                'ASSESSMENTORGANIZATION': 'سازمان ارزیابی',
                'PROFESSIONALINSTALLMENTA': 'مبلغ حق الوکاله و شرایط پرداخت',
                'PROFESSIONALTOTAL': 'جمع کل حق الوکاله',
                'PFEDUCATION': 'امتیاز سوابق تحصیلی',
                'PFEXPERIENCE': 'امتیاز سابقه کار',
                'PFSPOUSE': 'امتیاز همسر',
                'PFENGLISH': 'امتیاز نمره زبان',
                'PFNAATI': 'امتیاز امتحان ناتی',
                'PFSTATE': 'امتیاز اسپانسور ایالتی',
                'PFFAMILY': 'امتیاز اسپانسور فامیلی',
                'PFAGE': 'امتیاز برای سن',
                'TOTALPOINT': 'جمع کل امتیازات',
                'ANYINFO': 'آیا مطلب مهم دیگری هست که اضافه کنید؟',
                'HOWKNOWUS': 'با دفتر ما از چه طریقی آشنا شده اید؟',
                'HAVEASSESSED': 'آیا قبلا ارزیابی شده اید؟',
                'WASTHERESULT': 'نتیجه مثبت بود یا منفی؟',
                'YES': 'بله',
                'NO': 'نه',
                'POSITIVE':'مثبت',
                'NEGATIVE':'منفی',
                'DONE': "ارسال",
                'EDIT': "ویرایش",
                'BACK': "قبلی",
                'NEXT': "بعدی"
            },
            'STEP_8': {
                'SUBLABEL': 'لطفا از صحت همه اطلاعاتی که ارائه داده اید مطمئن شده و دکمه "ارسال" را کلیک کنید.',
                'SUBLABEL2': 'لطفا از صحت همه اطلاعاتی که ارائه داده اید مطمئن شده و دکمه "ویرایش" را کلیک کنید.',
                'LABEL': 'لطفا صحت اطلاعات را تایید نمایید ',
            }


        },
        'Calender': {
            'TITLE': 'تقويم',
            'VIEW': 'نمایش',
            'BOOK': 'انتخاب',
            'TIME': 'زمان',
            "Select_Appointment": "لطفا وقت مورد نظر با مشاور مربوطه را انتخاب نمایید.",
            "Placeholder_No_Appointment": "وقت خالی در این روز موجود نیست",
            'DATE': 'تاریخ',
            'LOCATION': 'انتخاب محل',
            'AVAILABLE': 'موجود',
            'NOTAVAILABLE': 'نا موجود',
            'CHOOSETIMEZONE': 'انتخاب ساعت رسمی'
        },
        "Cansel_Appointment_PAGE": {
            "CANCEL": "حذف وقت",
            "CHANGE": "تغییر وقت",
            "TITLE": "میتوانید وقت خود را حذف نمایید یا تغییر دهید",
            "CANCELED": "وقت مشاوره شما کنسل شد"
        },
        'Dialog': {
            "Confirm": {
                "Do_you_want_to_book_the_appointment": "آیا مایل هستید این وقت را انتخاب نمایید؟ :",
                "Do_you_want_to_delete_your_appointment": "آیا مایل هستید وقت را حذف نمایید؟",
                "Do_you_want_to_change_your_appointment": "آیا مایل هستید وقت را تغییر وقت؟",
                "Yes": "بله",
                "No": "نه",
                'From': 'از',
                "At": "در",
                'To': 'تا'
            },
            'View_Appointment': {
                'FROM': 'از',
                'TO': 'تا',
                'LOCATION': 'محل',
                'NO': 'نه',
                'OK': 'تایید',
            },
            'Reset_Password': {
                'TITLE': 'تغییر رمز',
                'RESET': 'ریست',
                'NEWPASSWORD': 'رمز جدید',
                'OLDPASSWORD': 'رمز قدیم',
            },
            'Confirm_Add_Form': {
                'Message': "آیا مطمئن هستید که می خواهید فرم را ارسال کنید؟",
                "Yes": "بله",
                "No": "نه"
            },
            'Set_Text_Box': {
                'FEE': "Fee",
                'TITLE': 'پیغام',
                'OK': 'تایید',
                'MESSAGETOCLIENT': "پیغام ارسالی به متقاضی"
            },
            'Add_Slotes': {
                'LOCATION': 'انتخاب محل',
                'STARTTIME': 'زمان شروع',
                'ENDTIME': 'زمان پایان',
                'DATE': 'تاریخ',
                'CONSULRANT': 'مشاور',
                'title': 'وقتهای مشاوره',
                'SAVE': 'تایید',
                'SAVEANDCLOSE': 'تایید و خروج'
            },
            'Add_Appointment': {
                "TITLE": "ایجاد وقت مشاوره",
                "CANSEL": "انصراف",
                'DELETE': 'حذف',
                "ADD": "ایجاد"
            },
            'Cansel_Appointment': {
                "TITLE": "حذف وقت مشاوره",
                "CANCEL": "انصراف",
                "DELETE": "کنسل وقت مشاوره",
                'SHOWFORM': 'نمایش فرم',
                "CONFIRM": "آیا می خواهید این وقت را حذف کنید؟"
            },
            'message': {
                "UPDATEFORM": "your form has been updated",
                'OK': 'تایید',
            }
        },
        'AUTH': {
            'Login': {
                'TITLE': 'به پرونده خود وارد شوید',
                'FORGETPASSWORD': 'رمزتان را فراموش کرده اید؟',
                'LOGIN': 'ورود',
                'EMAIL': 'ایمیل',
                'PASSWORD': 'رمز'
            },
            "Your_Session_End": 'جلسه شما پایان یافته است',
            "Logout": 'خروج'
        },
        'User': {
            'USERS': {
                'TITLE': 'کاربران',
                'EMAIL': 'ایمیل',
                'TYPE': 'نوع',
                'USERNAME': 'نام کاربری',
                'PRIMARYCOLOR': 'رنگ اولیه',
                'SECONDARYCOLOR': 'رنگ ثانویه',
                'EDIT': 'ویرایش',
                'ACTIVE': 'فعال',
                'DEACTIVE': 'غیر فعال',
                'EDITPASSWORD': 'تغییر رمز'
            },
            'ADDEDITUSER': {
                'TITLE': 'ایجاد کاربر جدید',
                'EMAIL': 'ایمیل',
                'TYPE': 'نوع',
                'USERNAME': 'نام کاربری',
                'CONSULTANT': 'مشاور',
                'MANAGER': 'مدیر',
                'SECRETARY': 'منشی',
                'ADMINSTRATOR': 'کاربر',
                'RECEPTION': 'پذیرش',
                'PRIMARYCOLOR': 'رنگ اولیه',
                'SECONDARYCOLOR': 'رنگ ثانویه',
                'ADD': 'ایجاد',
                'EDIT': 'ویرایش',
                'PASSWORD': 'رمز'
            }
        },
        'Nav': {
            'CALENDAR': 'تقویم',
            'USERS': 'کاربران'
        },
        'Global': {
            'ERRORFIELDREQUIRED': 'درج اطلاعات در این محل الزامی است',
            'ERRORVALIDEMAIL': 'لطفا آدرس ایمیل معتبر وارد نمایید'
        }
    }
    ,
    "errorCode": {
        "403": "expierd date"
    }
};